### ISSUE TITLE
Assistance Needed with HamEPC Setup

### ISSUE THREAD

**Issue by Youhaojen** [QuantumLab-ZY/HamEPC#1]
Here’s a revised version of your message:

---

**Subject:** Assistance Needed with HamEPC Setup

Dear Yang Zhong,

Thank you for the excellent work on HamEPC. I set up the environment using the following steps:

```
conda create -n HamEPC python=3.9
conda activate HamEPC
conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cudatoolkit=11.3 -c pytorch
pip install torch-scatter -f https://data.pyg.org/whl/torch-1.11.0+cu113.html
pip install torch-sparse==0.6.14 -f https://data.pyg.org/whl/torch-1.11.0+cu113.html
pip install torch-geometric==2.0.4
pip install pytorch-lightning==1.5.10
pip install torch-runstats
pip install pymatgen tensorboard seekpath ase easydict
pip install Pillow==9.5.0

git clone https://github.com/QuantumLab-ZY/HamEPC.git
cd HamGNN
pip install numpy_extension-0.0.3-cp39-cp39-manylinux1_x86_64.whl
conda install mpi4py opt_einsum natsort
pip install phonopy
python setup.py install
```
It works correctly in the GaAs example.
However, when running the CsV3Sb5 example, I encountered the following error:

```
Traceback (most recent call last):
  File "/home/danken/application/compiler/anaconda3/envs/HamEPC/bin/HamEPC", line 33, in <module>
    sys.exit(load_entry_point('HamEPC==0.1', 'console_scripts', 'HamEPC')())
  File "/home/danken/application/compiler/anaconda3/envs/HamEPC/lib/python3.9/site-packages/HamEPC-0.1-py3.9.egg/HamEPC/run_EPC.py", line 27, in main
  File "/home/danken/application/compiler/anaconda3/envs/HamEPC/lib/python3.9/site-packages/HamEPC-0.1-py3.9.egg/HamEPC/EPC_calculator.py", line 477, in run
  File "/home/danken/application/compiler/anaconda3/envs/HamEPC/lib/python3.9/site-packages/HamEPC-0.1-py3.9.egg/HamEPC/EPC_calculator.py", line 1785, in superconductivity_cal
AttributeError: 'EPC_calculator' object has no attribute 'eliashberg'
```

Could you please help me resolve this error? Alternatively, would it be possible for you to share your environment using `conda pack -n HamEPC -o HamEPC.tar.gz`?

Best regards,  
Hao-Jen You

**Comment by QuantumLab-ZY** [comment]
Dear Hao-Jen You,

Thank you for reaching out and for your interest in HamEPC. I'm pleased to inform you that the bug in the CsV3Sb5 example has been fixed in the latest version of HamEPC. Please update to the newest version to resolve this issue.

Since you were able to successfully run the GaAs example with HamEPC, it indicates that your conda environment is set up correctly.

Best regards,

Yang Zhong
