### ISSUE TITLE
KeyError: 'Mon' on mobility calculation of GaAs

### ISSUE THREAD

**Issue by Vahid999** [QuantumLab-ZY/HamEPC#7]
Thank you for sharing the HamEPC environment. I installed HamEPC and ran the mobility of GaAs. I changed read_momentum form False to True because it says so in the utility.py:

`'read_momentum': False, # When calculating the carrier mobility, read_momentum should be true.`

I get the following error:

`################################################## Mobility Calculation ##################################################
Sampling with Cauchy distribution.
Using ERTA method to calculate mobility.
Traceback (most recent call last):
  File "/home/vaskarpo/bin/NN/new_EPC/lib/python3.9/site-packages/torch_geometric/data/storage.py", line 78, in __getattr__
    return self[key]
  File "/home/vaskarpo/bin/NN/new_EPC/lib/python3.9/site-packages/torch_geometric/data/storage.py", line 103, in __getitem__
    return self._mapping[key]
KeyError: 'Mon'`

If I set read_momentum to False, nothing is put out even after 10 hours. 

Am I doing something wrong here? Maybe the neural network file for GaAs I downloaded from the link in your paper does not contain momentum data.

Thanks,
Vahid

**Comment by QuantumLab-ZY** [comment]
Dear @Vahid999,

The comment you mentioned is outdated and was left over from a previous version. Currently, `read_momentum` does not need to be enabled for calculating carrier mobility in HamEPC.

Best wishes,
Yang Zhong
